// SPDX-License-Identifier: GPL-3.0-or-later
#include "hakoniwa/drone/control_adapter/ap_altitude_control_backend.hpp"
#include <AC_PID/AC_P_1D.h>
#include <AC_PID/AC_PID.h>
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace hakoniwa::drone::control_adapter { namespace {
void validate(const ApAltitudeControlBackendConfig& c) { const double v[]{c.position_p,c.velocity_p,c.velocity_i,c.velocity_d,c.velocity_imax_mps2,c.velocity_filter_hz,c.velocity_derivative_filter_hz,c.velocity_feed_forward,c.acceleration_p,c.acceleration_i,c.acceleration_d,c.acceleration_imax,c.acceleration_target_filter_hz,c.acceleration_error_filter_hz,c.acceleration_derivative_filter_hz,c.acceleration_feed_forward,c.hover_thrust,c.speed_up_mps,c.speed_down_mps,c.acceleration_max_mps2,c.jerk_max_mps3,c.thrust_min,c.thrust_max}; for(double x:v)if(!std::isfinite(x)||x<0)throw std::invalid_argument("invalid ArduPilot altitude configuration"); if(c.hover_thrust<=0||c.thrust_min>c.thrust_max)throw std::invalid_argument("invalid ArduPilot altitude thrust range"); }
AC_PID::Defaults defs(double p,double i,double d,double ff,double imax,double tf,double ef,double df){return {float(p),float(i),float(d),float(ff),float(imax),float(tf),float(ef),float(df),0,1,0};}
void configure(AC_PID& p,double kp,double ki,double kd,double ff,double imax,double tf,double ef,double df){p.set_kP(kp);p.set_kI(ki);p.set_kD(kd);p.set_ff(ff);p.set_imax(imax);p.set_filt_T_hz(tf);p.set_filt_E_hz(ef);p.set_filt_D_hz(df);}
}
class ApAltitudeControlBackend::Impl { public: explicit Impl(const ApAltitudeControlBackendConfig& c):position(c.position_p),velocity(defs(c.velocity_p,c.velocity_i,c.velocity_d,c.velocity_feed_forward,c.velocity_imax_mps2,c.velocity_filter_hz,c.velocity_filter_hz,c.velocity_derivative_filter_hz)),acceleration(defs(c.acceleration_p,c.acceleration_i,c.acceleration_d,c.acceleration_feed_forward,c.acceleration_imax*1000,c.acceleration_target_filter_hz,c.acceleration_error_filter_hz,c.acceleration_derivative_filter_hz)){position.set_kP(c.position_p);position.set_limits(-c.speed_down_mps,c.speed_up_mps,c.acceleration_max_mps2,c.jerk_max_mps3);configure(velocity,c.velocity_p,c.velocity_i,c.velocity_d,c.velocity_feed_forward,c.velocity_imax_mps2,c.velocity_filter_hz,c.velocity_filter_hz,c.velocity_derivative_filter_hz);configure(acceleration,c.acceleration_p,c.acceleration_i,c.acceleration_d,c.acceleration_feed_forward,c.acceleration_imax*1000,c.acceleration_target_filter_hz,c.acceleration_error_filter_hz,c.acceleration_derivative_filter_hz);acceleration.set_imax(std::max(c.acceleration_imax,c.hover_thrust)*1000);} AC_P_1D position; AC_PID velocity,acceleration; };
ApAltitudeControlBackend::ApAltitudeControlBackend(const ApAltitudeControlBackendConfig& c){set_config(c);} ApAltitudeControlBackend::~ApAltitudeControlBackend()=default;
void ApAltitudeControlBackend::reset(){acceleration_target_mps2_=0;impl_->velocity.reset_I();impl_->velocity.reset_filter();impl_->acceleration.reset_I();impl_->acceleration.reset_filter();}
NormalizedVerticalThrustCommand ApAltitudeControlBackend::run(const AltitudeControlInput& in,double dt){if(!std::isfinite(dt)||dt<=0)throw std::invalid_argument("altitude dt must be positive"); double vt=in.target_velocity.vz; if(in.mode==AltitudeControlMode::Position){float target=in.target_altitude;vt+=impl_->position.update_all(target,in.position.z);}vt=std::clamp(vt,-config_.speed_down_mps,config_.speed_up_mps);double ar=impl_->velocity.update_all(vt,in.velocity.vz,dt,false)+impl_->velocity.get_ff();ar=std::clamp(ar,-config_.acceleration_max_mps2,config_.acceleration_max_mps2);double dc=config_.jerk_max_mps3*dt;acceleration_target_mps2_+=std::clamp(ar-acceleration_target_mps2_,-dc,dc);double throttle=config_.hover_thrust+.001*(impl_->acceleration.update_all(acceleration_target_mps2_*100,in.acceleration.az*100,dt,false)+impl_->acceleration.get_ff());double tc=1-2*(in.attitude.x*in.attitude.x+in.attitude.y*in.attitude.y);if(tc>.1)throttle/=tc;throttle=std::clamp(throttle,config_.thrust_min,config_.thrust_max);return{-throttle/config_.hover_thrust};}
void ApAltitudeControlBackend::set_config(const ApAltitudeControlBackendConfig& c){validate(c);config_=c;impl_=std::make_unique<Impl>(c);reset();}
}
